### ISSUE TITLE
Add support for FormPicker datatype propertyeditor

### ISSUE THREAD

**Issue by PhilA1** [logikfabrik/uJet#22]
Need a DataTypeDefinition for FormPicker : 1167 please.

Or allow UIHint to be numeric and match on propertyeditor.nodeId instead of Alias if that is possible?

**Comment by logikfabrik** [comment]
Thanks for the feature request. I'll look in to it!

**Comment by fremler** [comment]
The UiHint Attribute seem to be broken, for content picker at least. 
In addition to what PhilA1 said, I think it would be better if you target a data type with an ID instead of the alias.

**Comment by logikfabrik** [comment]
I'm currently rewriting parts concerning the UI hints. I'll have a look at both the content and the form picker.

**Comment by logikfabrik** [comment]
This project is no longer being maintained. Closing.
