### ISSUE TITLE
Nested templates in Backoffice

### ISSUE THREAD

**Issue by ActionCommunity** [logikfabrik/uJet#5]
In Umbraco with installed fanoe starter kit, uJet copies the 5 nested templates under the fanoe home on every start into the root of the templates in the backoffice menu. So uJet needs to take care about nested templates.

Do you have a workaround how to switch templating sync off?

**Comment by logikfabrik** [comment]
I'm not that familiar with the tooling for nested templates in the Umbraco back office. The main focus for uJet has been type synchronization, using views created in VS. I'll look in to it, must be a bug.

You can turn template synchronization off. But it means disabling synchronization for document types altogether I'm afraid. I'll look into this too; adding a switch to turn template synchronization off.

**Comment by ActionCommunity** [comment]
Hello,
I'm familiar with that stuff. I'm very interested on using you tool. Maybe you are interested on a contributor? So I can fix that in a several branch which you later can use when packaging the next version of uJet. I find the way you are getting information about entities by using standard data annotation attributes. I have some ideas and needs for such an helper in unreal which we maybe can add to uJet. Let me know if you ate interested in assistance.
Michael
Am 18.12.2015 07:31 schrieb Anton Frennevi <notifications@github.com>:I'm not that familiar with the tooling for nested templates in the Umbraco back office. The main focus for uJet has been type synchronization, using views created in VS. I'll look in to it, must be a bug.

You can turn template synchronization off. But it means disabling synchronization for document types altogether I'm afraid. I'll look into this too; adding a switch to turn template synchronization off.

**Comment by ActionCommunity** [comment]
Umbraco does not treat the filenames with lower case charachter on first place when creating the aliases. Changed that behavior in TemplateSynchronizationService seems to fix that bug. Please review it. Thank you.

**Comment by logikfabrik** [comment]
I closed the pull request for Master; I feel we need to look this over some more before merging it.

I think you're right about the lowercase/uppercase issue, ignoring case when synchronizing templates fixes the issue with multiple templates - as far as I can see.

Having uJet figure out the master/child view relationship is tricky. Say you've created a .cshtml file, but you haven't set it up in the back office. How would uJet know if you want the file to be a master or a child view? Sure, we could examine the actual file contents, looking for the Layout assignment. But that feels fragile. Is it possible to jack into the Razor view engine and leave the tricky parts to the MVC framework?

**Comment by ActionCommunity** [comment]
Hey,

 

I just thought about that too. Currently I have no idea, but I will get one. Does not work, does not exists. I think we need to invest some more time to correct the template synchronization.

 

One idea of me was to use razor and a custom base page implementation to let the .cshtml set the layout. On another side, I want to review the Umbraco source code to find out how they are doing that, because they are doing that. At last, we need to setup integration tests for the whole layer to check out my strange effects on the templating stuff, how I said, we need to invest much more time to get it rid.

 

Let me know when you get an idea, if you get one. Otherwise I will invest some time over Christmas to fix that.

 

On Umbraco side it is not an problem to find out nested templates. The templates have an property Master or something where we can get it. So find out how Umbraco is doing that will not be hard, only show all references of this property in source and all will be fine. Because the small letter / upper letter fix should work, maybe Umbraco has an problem with his services. Um using the newest one 7.3.4 for my tests.

 

So stay tuned! :)

 

Michael

**Comment by logikfabrik** [comment]
Just commited a fix for nested templates. I looked through the Umbraco source, found a method matching what you've talked about; SetMasterTemplate(...).

There's no clean way of getting the layout/master from a .cshtml file though, so I had to resort to some regexp. I've done a couple tests using the Fanoe kit and it all looks good.

**Comment by ActionCommunity** [comment]
Hey,

 

nice. Have you looked into your folder physically? I have had there everytime a file with the same name as original but with a lower case or has my last fix I checked in working as expected?

 

Michael

**Comment by logikfabrik** [comment]
Yes, I have. With a fresh setup of Fanoe, with the latest dev build of uJet, there are no longer any duplicate views being created. And nested templates works.

**Comment by ActionCommunity** [comment]
Nice, okay my time was to short to realize that, but nice that I can help with an idea at least :) have a nice day
Am 22.12.2015 08:10 schrieb Anton Frennevi <notifications@github.com>:Yes, I have. With a fresh setup of Fanoe, with the latest dev build of uJet, there are no longer any duplicate views being created. And nested templates works.

**Comment by logikfabrik** [comment]
:) If you have the time, it would be awesome if you could have a look at nested document types later.

I'll mark this issue for v 3.5 and close it.

**Comment by ActionCommunity** [comment]
Anton,
Yeah I just want top test that stuff today or lately tomorrow. Maybe today in the night, currently I'm designing a 5 billion euro software which takes most of my time, but I will find a hour the next 2 days! I'm working for Gdfsuez Europe and they currently plan top realize 3 mega projects with me and my software developer team in leading.
While I'm driving 2 hours every day in Berlin, I have much time to think. So I thought about the nesting document type problem. My suggestion is:
- add a new property to the document type attribute named NestWithPatentClass
- synchronization then needs to be done in 3 steps:
1. Parse out only direct properties of the class with this attribute
2. Store the new document types
3. Add the master relation to the document type in Umbraco where it's needed
What do you think? Should work, or?
Michael
Am 22.12.2015 13:31 schrieb Anton Frennevi <notifications@github.com>::) If you have the time, it would be awesome if you could have a look at nested document types later.

I'll mark this issue for v 3.5 and close it.

**Comment by ActionCommunity** [comment]
Hello,

 

so I have tested it out, for me all seems to work.

 

Merry Christmas!

 

Michael
