### ISSUE TITLE
No nesting on document types by using nested classes

### ISSUE THREAD

**Issue by ActionCommunity** [logikfabrik/uJet#6]
When I have a class attributes with DocumentTypeAttribute and another one which derrives from the first one, I expext that the document types are created a nested way, which means, that the document type 2 is located under the document type 1 in umbraco backoffice. For this, you dont need to redefine all properties on every level, and this behavior is more closer to the real c# implentation.

> Or is it no bug and this was nehavior of a decision of you?

__Class 1__
```
#if WEB
    [PreviewTemplateAttribute]
    [DocumentType("90F7F7E7-4906-41B2-A48E-BBAAAAAAAAAA", "Web",
    AllowedAsRoot = false,
    Description = "Base document for all umbraco pages."
    )] 
#endif
    /// <summary>
    /// Base Document Type for all document types.
    /// </summary>
    public class BaseDocumentType
    {
#if DATA
        [ScaffoldColumn(false)]
        [Display(Name = "Id", GroupName = "Properties")]
#endif
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime Created { get; set; }

        public DateTime PublishedAt { get; set; }
    }
```

__Class 2__
```
#if WEB
    [PreviewTemplateAttribute]
    [DocumentType("90F7F7E7-4906-41B2-A48E-BBAAAAAAAAAB", "Platform",
        
        AllowedAsRoot = true,
        Description = "Defines a platform which is the root document of all web's.",
        AllowedChildNodeTypes = new[] { typeof(FreeMarkupContentDocument) }
    )]
#endif
    public class Platform : BaseDocumentType
    {
#if DATA
        [MaxLength(500)]
        [Display(AutoGenerateField = true,
            Description = "The slogan of your platform.",
            Name = "Slogan",
            Order = 100,
            GroupName = "Platform")]

#endif
        public string Slogan { get; set; }
    }
```

**Comment by logikfabrik** [comment]
This is not a bug, but a decision I made when first writing the synchronization services. You do have a point and I suspect others might expect that behaviour as well. I'll see what I can do. Thanks for pointing it out!

**Comment by ActionCommunity** [comment]
Hello,
Okay I understand. Maybe you can make this possible by using a property on the DocumentType attribute.
Michael
Am 18.12.2015 07:41 schrieb Anton Frennevi <notifications@github.com>:This is not a bug, but a decision I made when first writing the synchronization services. You do have a point and I suspect others might expect that behaviour as well. I'll see what I can do. Thanks for pointing it out!

**Comment by logikfabrik** [comment]
I've made major changes to the sync logic to allow for composition (document and media types only). I haven't had the time to do any test yet, so there might be some bugs. I've also found some issues when using the ID attribute for types.

uJet now looks at type inheritance and sets up composition if it find more than 1 document/media type in the inheritance chain.

I'm sure there's a lot more to do, but it's a start. :)

**Comment by ActionCommunity** [comment]
Hey,

 

that sounds good. I will give it a try now when it’s in DEV branch. I find some minutes today, let you know how is it working for me.

 

Michael

**Comment by ActionCommunity** [comment]
Hello,

 

yes that is working. I expected to find the derrived class directly in a master assignment. Document Type compositions in umbraco are possible over two ways:

*       Compositions like you has done it

*       And a direct composition

When you click right in Backoffice you can say > Create, when you now create a document type it will be nested directly under the document type you right clicked.

 

So maybe adjusting your nice working system can be helpful:

-        Realize the nesting with direct composition

-        Add a new property to DocumentTypeAttribute ComposedTypes or something where you can put in additional composings of document types

This is only a suggestion, you way is working fine for me. But if you think about the stuff above, you must take care about the exception handling. Because composing with many document types leads fast into circular references. In this case the user should get a good message on which document type composition the save error occurred.

 

Nice work, well done!!

 

Happy new year to Sweden!!

 

Michael

**Comment by ActionCommunity** [comment]
Anton,

 

one bug I noticed: the document types are imported even when no settings are in web.config. Maybe the standard value is not correct or something, I have not looked into the code, but the behavior was there.

 

Michael

**Comment by logikfabrik** [comment]
I didn't know about direct inheritance in Umbraco; I only knew about composition. Good catch! We'll need to get that working too.

Composition, is that like multiple inheritance? You have 2 document types, then you set another document type to "inherit" from both? Going with an attribute as you suggest might be better.

I'm rewriting the sync services right now (no new features or anything, just removing duplicate code using generics).

**Comment by ActionCommunity** [comment]
Anton,

 

yeah, with this multiple composition you can compose many document types with one. The nested way is the direct inheritance (but shown in backoffice under Structure > Compositions in gray and Is selected when used). Try it, take a document type, add another one directly under it, and then try using the compositions.

 

This is not used often. In real big umbraco apps Im using only the direct inheritance because it is very easy to move into classes in backend. I added a screenshot to clarify this.

 



 

Michael

**Comment by logikfabrik** [comment]
OK! I misunderstood the concept of composition. Using code inheritance like today isn't the way to go (that's how direct inheritance should work). So I'm with you on implementing composition using a property on the ContentTypeAttribute (CompositionTypes).

I just commited a major rewrite on the sync services. It should be much easier to follow the flow now. Once again, I haven't done that many tests. Sorry! :)

If you have time, maybe you can have a look at composition and direct inheritance? You have an understanding of how Umbraco works that I don't.

**Comment by logikfabrik** [comment]
uJet now supports inheritance and composition.
